### ISSUE TITLE
more of a question rather then an issue... can you to anything with their api: 

### ISSUE THREAD

**Issue by mladencucak** [krose/yrno#1]
Can you use their api? I am not realy familiar with parsing xml files and would  love to use their 10 day forecast and see if it is better than one provided by met office here in Ireland
https://api.met.no/weatherapi/locationforecastlts/1.3/?lat=52.86;lon=-6.91;msl=61

**Comment by krose** [comment]
I don't have time to look at it. You might wan't to learn about the xml2 package. Here's some info on the xml2 package that you wan't to use: http://xml2.r-lib.org/
